// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713043415_AddProductToDbAndSeedTable")]
    partial class AddProductToDbAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "aayush"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "stha"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "avi"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Frank Herbert",
                            Description = "A sweeping science fiction epic set on the desert planet Arrakis, following Paul Atreides as he navigates politics, prophecy, and survival.",
                            ISBN = "9780441013593",
                            ListPrice = 45m,
                            Price = 40m,
                            Price100 = 30m,
                            Price50 = 35m,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert C. Martin",
                            Description = "A handbook of agile software craftsmanship, covering principles and practices for writing maintainable, readable code.",
                            ISBN = "9780132350884",
                            ListPrice = 55m,
                            Price = 50m,
                            Price100 = 40m,
                            Price50 = 45m,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            Description = "A reluctant hobbit, Bilbo Baggins, sets out on an unexpected journey to help a group of dwarves reclaim their homeland from a dragon.",
                            ISBN = "9780547928227",
                            ListPrice = 35m,
                            Price = 30m,
                            Price100 = 24m,
                            Price50 = 27m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 4,
                            Author = "James Clear",
                            Description = "A practical guide to building good habits and breaking bad ones, using small, incremental changes.",
                            ISBN = "9780735211292",
                            ListPrice = 30m,
                            Price = 27m,
                            Price100 = 20m,
                            Price50 = 24m,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 5,
                            Author = "George Orwell",
                            Description = "A dystopian novel depicting a totalitarian regime that enforces absolute control through surveillance and propaganda.",
                            ISBN = "9780451524935",
                            ListPrice = 25m,
                            Price = 22m,
                            Price100 = 16m,
                            Price50 = 19m,
                            Title = "1984"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
